### ISSUE TITLE
Add missing sonar.basePlugin property

### ISSUE THREAD

**Issue by ankitdadhich** [racodond/sonar-css-custom-rules-plugin#5]
Hi David,

I am having bit difficulty in putting custom rule.

Whenever I copy and paste `sonar-csscustomrules-plugin-1.0.jar` to plugins folder SonarQube crashes.

I tried it plenty of time, it works fine when I remove the `sonar-csscustomrules-plugin-1.0.jar` .

Not sure am I doing anything wrong? very less info is available on internet as well.

Note : I tried to debug log. It says version of css-plugin should be 4.13 or higher. I have appropriate version(see screenshot below.)  But still it fails.

Thanks
Ankit

![image](https://user-images.githubusercontent.com/9630673/37030288-042a77c8-216d-11e8-96f4-1e25fa132d44.png)

[access.log](https://github.com/racodond/sonar-css-custom-rules-plugin/files/1784760/access.log)
[ce.log](https://github.com/racodond/sonar-css-custom-rules-plugin/files/1784761/ce.log)
[es.log](https://github.com/racodond/sonar-css-custom-rules-plugin/files/1784762/es.log)
[sonar.log](https://github.com/racodond/sonar-css-custom-rules-plugin/files/1784763/sonar.log)
[web.log](https://github.com/racodond/sonar-css-custom-rules-plugin/files/1784764/web.log)

**Comment by racodond** [comment]
The error seems crystal clear in the ce.log file:

```
2018.03.06 16:07:01 ERROR ce[][o.s.ce.app.CeServer] Compute Engine startup failed
org.sonar.updatecenter.common.exception.IncompatiblePluginVersionException: The plugin 'css' is in version 3.1 whereas the plugin 'csscustomrules' requires a least a version 4.13.
	at org.sonar.updatecenter.common.PluginReferential.addOutgoingDependency(PluginReferential.java:135)
...
```

**Comment by ankitdadhich** [comment]
Thus why I posted screenshot in question. I don't know why this is still showing the version error while I am on 4.13.
![image](https://user-images.githubusercontent.com/9630673/37031268-b95f39c8-2170-11e8-8820-23c53b2a41a4.png)

**Comment by racodond** [comment]
Have you restarted the server after upgrading?

**Comment by ankitdadhich** [comment]
Yes I did. But can't go to Webinterface now. as it keeps on showing its on maintenance.
Is there any other command to restart?

**Comment by racodond** [comment]
I'll let you fix the issue with your SonarQube server. Come back to me when it's up and working again.

**Comment by racodond** [comment]
I've found out an issue. I'll work on it and keep you posted.

**Comment by racodond** [comment]
Could you try again with https://github.com/racodond/sonar-css-custom-rules-plugin/releases/tag/1.1 ?

**Comment by ankitdadhich** [comment]
Thank you. It's working fine now. :)

**Comment by racodond** [comment]
Cool! Thanks for the feedback!
