### ISSUE TITLE
ce[o.s.ce.app.CeServer] Compute Engine startup failed

### ISSUE THREAD

**Issue by JAKTHARKHAN** [racodond/sonar-css-custom-rules-plugin#6]
Hi,

When I tried starting SonarQube server, wrapper is getting started and stopping with the below error. Seems to be "plsql' plugin causing the issue and am not sure what could resolve this.
Could you please check the below error log and help..?? Also attaching plsql plugin here which I have.
[sonar-plsql-open-plugin-2.0.0-SNAPSHOT.jar.zip](https://github.com/racodond/sonar-css-custom-rules-plugin/files/3328592/sonar-plsql-open-plugin-2.0.0-SNAPSHOT.jar.zip)
NOTE - content in the BOLD format shows the error.

--> Wrapper Started as Console
Launching a JVM...
Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
  Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.

2019.06.26 11:36:36 INFO  app[o.s.a.AppFileSystem] Cleaning or creating temp directory D:\Agile\NewSonarQube\sonarqube-5.6.6\temp
2019.06.26 11:36:39 INFO  app[o.s.p.m.JavaProcessLauncher] Launch process[es]: D:\Agile\Java\jdk1.8.0_65\jre\bin\java -Djava.awt.headless=true -Xmx1G -Xms256m -Xss256k -Djava.net.preferIPv4Stack=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=D:\Agile\NewSonarQube\sonarqube-5.6.6\temp -javaagent:D:\Agile\Java\jdk1.8.0_65\jre\lib\management-agent.jar -cp ./lib/common/*;./lib/search/* org.sonar.search.SearchServer D:\Agile\NewSonarQube\sonarqube-5.6.6\temp\sq-process596459889577119410properties
2019.06.26 11:36:42 INFO   es[o.s.p.ProcessEntryPoint]  Starting es
2019.06.26 11:36:42 INFO   es[o.s.s.EsSettings]  Elasticsearch listening on 127.0.0.1:9001
2019.06.26 11:36:42 INFO   es[o.elasticsearch.node]  [sonar-1561529196380] version[1.7.5], pid[3268], build[00f95f4/2016-02-02T09:55:30Z]
2019.06.26 11:36:42 INFO   es[o.elasticsearch.node]  [sonar-1561529196380] initializing ...
2019.06.26 11:36:42 INFO   es[o.e.plugins]  [sonar-1561529196380] loaded [], sites []
2019.06.26 11:36:43 INFO   es[o.elasticsearch.env]  [sonar-1561529196380] using [1] data paths, mounts [[(D:)]], net usable_space [55.7gb], net total_space [131.9gb], types [NTFS]
2019.06.26 11:36:44 WARN   es[o.e.bootstrap]  JNA not found. native methods will be disabled.
2019.06.26 11:36:45 INFO   es[o.elasticsearch.node]  [sonar-1561529196380] initialized
2019.06.26 11:36:45 INFO   es[o.elasticsearch.node]  [sonar-1561529196380] starting ...
2019.06.26 11:36:46 INFO   es[o.e.transport]  [sonar-1561529196380] bound_address {inet[/127.0.0.1:9001]}, publish_address {inet[/127.0.0.1:9001]}
2019.06.26 11:36:46 INFO   es[o.e.discovery]  [sonar-1561529196380] sonarqube/TEsGhyiBSDevbs8tMYzPow
2019.06.26 11:36:49 INFO   es[o.e.cluster.service]  [sonar-1561529196380] new_master [sonar-1561529196380][TEsGhyiBSDevbs8tMYzPow][CLBBLR-5070][inet[/127.0.0.1:9001]]{rack_id=sonar-1561529196380}, reason: zen-disco-join (elected_as_master)
2019.06.26 11:36:49 INFO   es[o.elasticsearch.node]  [sonar-1561529196380] started
2019.06.26 11:36:49 INFO   es[o.e.gateway]  [sonar-1561529196380] recovered [6] indices into cluster_state
2019.06.26 11:36:58 INFO  app[o.s.p.m.Monitor] Process[es] is up
2019.06.26 11:36:58 INFO  app[o.s.p.m.JavaProcessLauncher] Launch process[web]: D:\Agile\Java\jdk1.8.0_65\jre\bin\java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djruby.management.enabled=false -Djruby.compile.invokedynamic=false -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Djava.io.tmpdir=D:\Agile\NewSonarQube\sonarqube-5.6.6\temp -javaagent:D:\Agile\Java\jdk1.8.0_65\jre\lib\management-agent.jar -cp ./lib/common/*;./lib/server/*;D:\Agile\NewSonarQube\sonarqube-5.6.6\lib\jdbc\postgresql\postgresql-9.3-1102-jdbc41.jar org.sonar.server.app.WebServer D:\Agile\NewSonarQube\sonarqube-5.6.6\temp\sq-process7691079545239967638properties
2019.06.26 11:37:00 INFO  web[o.s.p.ProcessEntryPoint] Starting web
2019.06.26 11:37:03 INFO  web[o.s.s.a.TomcatContexts] Webapp directory: D:\Agile\NewSonarQube\sonarqube-5.6.6\web
2019.06.26 11:37:04 INFO  web[o.a.c.h.Http11NioProtocol] Initializing ProtocolHandler ["http-nio-0.0.0.0-9000"]
2019.06.26 11:37:04 INFO  web[o.a.t.u.n.NioSelectorPool] Using a shared selector for servlet write/read
2019.06.26 11:37:07 INFO  web[o.s.s.p.ServerImpl] SonarQube Server / 5.6.6 / e8e13145497bb920921ae4fe11b09f0903f1d298
2019.06.26 11:37:07 INFO  web[o.sonar.db.Database] Create JDBC data source for jdbc:postgresql://localhost/sonar
2019.06.26 11:37:09 INFO  web[o.s.s.p.DefaultServerFileSystem] SonarQube home: D:\Agile\NewSonarQube\sonarqube-5.6.6
2019.06.26 11:37:09 INFO  web[o.e.plugins] [sonar-1561529196380] loaded [], sites []
2019.06.26 11:37:10 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin Android / 1.1 / 9ab2bbcc83177e67c74d365f009bfe05bf38c7e3
2019.06.26 11:37:10 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin C# / 6.3.0.2862 / 1600df4ea68defd03b270da8e2935cfbf342cd8e
2019.06.26 11:37:10 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin CSS / SCSS / Less / 3.1 / 58a0a86a53f82a8486a5ee93681257e1ae0a10c8
2019.06.26 11:37:10 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin Checkstyle / 3.7 / 
2019.06.26 11:37:10 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin Cobertura / 1.7 / d14b7978322d19a2795286ebfed225a57b13c3af
2019.06.26 11:37:10 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin CodeCracker for C# / 1.0.1
2019.06.26 11:37:10 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin ESLint / 0.1.1
2019.06.26 11:37:10 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin PMD / 2.6 / f419f834b4bea51f9b6da33517b7f6186db5c066
2019.06.26 11:37:10 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin SonarJS / 3.1.1.5128 / 564d130c281685fde03e85964417158e32a17b2b
2019.06.26 11:37:10 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin SonarJava / 4.12.0.11033 / fa9fe66b0cb1b6ab8d7f341cc1f7908897a9cf33
2019.06.26 11:37:10 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin SonarPHP / 2.11.0.2485 / 741861a29e5f9a26c6c99c06268facb6c4f4a882
2019.06.26 11:37:10 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin SonarXML / 1.4.3.1027 / 39588245cecf538bb27be4e496ff303b0143d20b
2019.06.26 11:37:10 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin Sonargraph / 3.5
2019.06.26 11:37:10 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin Timeline / 1.5 / a9cae1328fd455a128b5d7d603381f47398c6e2a
2019.06.26 11:37:10 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin TypeScript / 1.2.0-rc1
2019.06.26 11:37:10 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin Web / 2.5.0.476 / 636872f5d37fa7a440fe07d08d504e1a881225e5
2019.06.26 11:37:14 INFO  web[o.s.s.p.RailsAppsDeployer] Deploying Ruby on Rails applications
2019.06.26 11:37:16 INFO  web[o.s.s.p.UpdateCenterClient] Update center: https://update.sonarsource.org/update-center.properties (no proxy)
2019.06.26 11:37:18 INFO  web[o.s.s.n.NotificationService] Notification service started (delay 60 sec.)
2019.06.26 11:37:18 INFO  web[o.s.s.s.RegisterMetrics] Register metrics
2019.06.26 11:37:18 INFO  web[o.s.s.r.RegisterRules] Register rules
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:InvalidReferenceToObject
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:NvlWithNullParameter
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:SameBranch
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:AddParenthesesInNestedExpression
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:CollapsibleIfStatements
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:DeclareSectionWithoutDeclarations
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:UselessParenthesis
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:CursorBodyInPackageSpec
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule common-plsqlopen:InsufficientCommentDensity
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule common-plsqlopen:InsufficientLineCoverage
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:EmptyStringAssignment
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:SelectWithRownumAndOrderBy
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:UnnecessaryNullStatement
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:VariableHiding
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:UnnecessaryElse
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:UnusedVariable
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:CommitRollback
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule common-plsqlopen:SkippedUnitTests
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:UnnecessaryAliasInQuery
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:UnusedParameter
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:ReturnOfBooleanExpression
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:DbmsOutputPut
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:IfWithExit
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:InsertWithoutColumns
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:VariableInCount
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:FunctionWithOutParameter
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:UnusedCursor
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:EmptyBlock
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:TooManyRowsHandler
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:ExplicitInParameter
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:ComparisonWithBoolean
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:QueryWithoutExceptionHandling
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:DuplicateConditionIfElsif
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule common-plsqlopen:FailedUnitTests
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:UnhandledUserDefinedException
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:ColumnsShouldHaveTableName
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:VariableInitializationWithNull
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:DuplicatedValueInIn
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:CharacterDatatypeUsage
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:RaiseStandardException
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule common-plsqlopen:InsufficientBranchCoverage
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:NotASelectedExpression
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:SameCondition
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:VariableInitializationWithFunctionCall
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:SelectAllColumns
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:ComparisonWithNull
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule common-plsqlopen:DuplicatedBlocks
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:IdenticalExpression
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:DeadCode
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:ParsingError
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:NotFound
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:InequalityUsage
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:ToDateWithoutFormat
2019.06.26 11:37:22 INFO  web[o.s.s.r.RegisterRules] Disable rule plsql:ConcatenationWithNull
2019.06.26 11:37:23 INFO  web[o.s.s.q.RegisterQualityProfiles] Register quality profiles
2019.06.26 11:37:26 INFO  web[o.s.s.s.RegisterNewMeasureFilters] Register measure filters
2019.06.26 11:37:26 INFO  web[o.s.s.s.RegisterDashboards] Register dashboards
2019.06.26 11:37:26 INFO  web[o.s.s.s.RegisterPermissionTemplates] Register permission templates
2019.06.26 11:37:26 INFO  web[o.s.s.s.RenameDeprecatedPropertyKeys] Rename deprecated property keys
2019.06.26 11:37:26 INFO  web[o.s.s.e.IndexerStartupTask] Index activities
2019.06.26 11:37:27 INFO  web[o.s.s.e.IndexerStartupTask] Index issues
2019.06.26 11:37:28 INFO  web[o.s.s.e.IndexerStartupTask] Index tests
2019.06.26 11:37:28 INFO  web[o.s.s.e.IndexerStartupTask] Index users
2019.06.26 11:37:28 INFO  web[o.s.s.e.IndexerStartupTask] Index views
2019.06.26 11:37:28 INFO  web[jruby.rack] jruby 1.7.9 (ruby-1.8.7p370) 2013-12-06 87b108a on Java HotSpot(TM) 64-Bit Server VM 1.8.0_65-b17 [Windows 7-amd64]
2019.06.26 11:37:28 INFO  web[jruby.rack] using a shared (threadsafe!) runtime
2019.06.26 11:37:49 INFO  web[jruby.rack] keeping custom (config.logger) Rails logger instance
2019.06.26 11:37:49 INFO  web[o.s.s.p.MasterServletFilter] Initializing servlet filter org.sonar.server.authentication.InitFilter@729695d6 [pattern=/sessions/init/*]
2019.06.26 11:37:49 INFO  web[o.s.s.p.MasterServletFilter] Initializing servlet filter org.sonar.server.authentication.OAuth2CallbackFilter@2dfc6340 [pattern=/oauth2/callback/*]
2019.06.26 11:37:50 INFO  web[o.a.c.h.Http11NioProtocol] Starting ProtocolHandler ["http-nio-0.0.0.0-9000"]
2019.06.26 11:37:50 INFO  web[o.s.s.a.TomcatAccessLog] Web server is started
2019.06.26 11:37:50 INFO  web[o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2019.06.26 11:37:50 INFO  app[o.s.p.m.Monitor] Process[web] is up
2019.06.26 11:37:50 INFO  app[o.s.p.m.JavaProcessLauncher] Launch process[ce]: D:\Agile\Java\jdk1.8.0_65\jre\bin\java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Djava.io.tmpdir=D:\Agile\NewSonarQube\sonarqube-5.6.6\temp -javaagent:D:\Agile\Java\jdk1.8.0_65\jre\lib\management-agent.jar -cp ./lib/common/*;./lib/server/*;./lib/ce/*;D:\Agile\NewSonarQube\sonarqube-5.6.6\lib\jdbc\postgresql\postgresql-9.3-1102-jdbc41.jar org.sonar.ce.app.CeServer D:\Agile\NewSonarQube\sonarqube-5.6.6\temp\sq-process7946359949307508495properties
2019.06.26 11:37:51 INFO  ce[o.s.p.ProcessEntryPoint] Starting ce
2019.06.26 11:37:51 INFO  ce[o.s.ce.app.CeServer] Compute Engine starting up...
2019.06.26 11:37:51 INFO  ce[o.s.s.p.ServerImpl] SonarQube Server / 5.6.6 / e8e13145497bb920921ae4fe11b09f0903f1d298
2019.06.26 11:37:51 INFO  ce[o.sonar.db.Database] Create JDBC data source for jdbc:postgresql://localhost/sonar
2019.06.26 11:37:52 INFO  ce[o.s.s.p.DefaultServerFileSystem] SonarQube home: D:\Agile\NewSonarQube\sonarqube-5.6.6
2019.06.26 11:37:52 INFO  ce[o.e.plugins] [sonar-1561529196380] loaded [], sites []
2019.06.26 11:37:53 INFO  ce[o.s.c.c.CePluginRepository] Load plugins
_**2019.06.26 11:37:58 ERROR ce[o.s.ce.app.CeServer] Compute Engine startup failed
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "ce_activity_uuid"
  Detail: Key (uuid)=(AWpKhMdKhBAmaVnZ4vza) already exists.
### Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "ce_activity_uuid"_
  Detail: Key (uuid)=(AWpKhMdKhBAmaVnZ4vza) already exists.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26) ~[mybatis-3.2.7.jar:3.2.7]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:154) ~[mybatis-3.2.7.jar:3.2.7]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:141) ~[mybatis-3.2.7.jar:3.2.7]
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:51) ~[mybatis-3.2.7.jar:3.2.7]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52) ~[mybatis-3.2.7.jar:3.2.7]
	at com.sun.proxy.$Proxy39.insert(Unknown Source) ~[na:na]
	at org.sonar.db.ce.CeActivityDao.insert(CeActivityDao.java:51) ~[sonar-db-5.6.6.jar:na]
	at org.sonar.ce.queue.CeQueueImpl.remove(CeQueueImpl.java:181) ~[sonar-server-5.6.6.jar:na]
	at org.sonar.ce.queue.CeQueueImpl.cancelImpl(CeQueueImpl.java:156) ~[sonar-server-5.6.6.jar:na]
	at org.sonar.server.computation.queue.InternalCeQueueImpl.cancel(InternalCeQueueImpl.java:128) ~[sonar-server-5.6.6.jar:na]
	at org.sonar.server.computation.queue.CeQueueCleaner.verifyConsistency(CeQueueCleaner.java:81) ~[sonar-server-5.6.6.jar:na]
	at org.sonar.server.computation.queue.CeQueueCleaner.clean(CeQueueCleaner.java:59) ~[sonar-server-5.6.6.jar:na]
	at org.sonar.server.computation.queue.CeQueueInitializer.initCe(CeQueueInitializer.java:59) ~[sonar-server-5.6.6.jar:na]
	at org.sonar.server.computation.queue.CeQueueInitializer.onServerStart(CeQueueInitializer.java:51) ~[sonar-server-5.6.6.jar:na]
	at org.sonar.server.platform.ServerLifecycleNotifier.notifyStart(ServerLifecycleNotifier.java:67) ~[sonar-server-5.6.6.jar:na]
	at org.sonar.ce.container.ComputeEngineContainerImpl.startupTasks(ComputeEngineContainerImpl.java:631) ~[sonar-ce-5.6.6.jar:na]
	at org.sonar.ce.container.ComputeEngineContainerImpl.start(ComputeEngineContainerImpl.java:619) ~[sonar-ce-5.6.6.jar:na]
	at org.sonar.ce.ComputeEngineImpl.startup(ComputeEngineImpl.java:43) ~[sonar-ce-5.6.6.jar:na]
	at org.sonar.ce.app.CeServer$CeMainThread.startup(CeServer.java:175) [sonar-ce-5.6.6.jar:na]
	at org.sonar.ce.app.CeServer$CeMainThread.attemptStartup(CeServer.java:165) [sonar-ce-5.6.6.jar:na]
	at org.sonar.ce.app.CeServer$CeMainThread.run(CeServer.java:153) [sonar-ce-5.6.6.jar:na]
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "ce_activity_uuid"
  Detail: Key (uuid)=(AWpKhMdKhBAmaVnZ4vza) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:412) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:44) ~[mybatis-3.2.7.jar:3.2.7]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:69) ~[mybatis-3.2.7.jar:3.2.7]
	at org.apache.ibatis.executor.ReuseExecutor.doUpdate(ReuseExecutor.java:50) ~[mybatis-3.2.7.jar:3.2.7]
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:105) ~[mybatis-3.2.7.jar:3.2.7]
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:71) ~[mybatis-3.2.7.jar:3.2.7]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:152) ~[mybatis-3.2.7.jar:3.2.7]
	... 19 common frames omitted
2019.06.26 11:37:58 INFO  app[o.s.p.m.Monitor] Process[ce] is up
2019.06.26 11:37:58 INFO  app[o.s.p.m.Monitor] Process[web] is stopping
2019.06.26 11:37:59 INFO  web[o.s.p.StopWatcher] Stopping process
2019.06.26 11:37:59 INFO  web[o.a.c.h.Http11NioProtocol] Pausing ProtocolHandler ["http-nio-0.0.0.0-9000"]
2019.06.26 11:38:00 INFO  web[o.s.s.n.NotificationService] Notification service stopped
2019.06.26 11:38:00 INFO  web[o.a.c.h.Http11NioProtocol] Stopping ProtocolHandler ["http-nio-0.0.0.0-9000"]
2019.06.26 11:38:01 INFO  web[o.a.c.h.Http11NioProtocol] Destroying ProtocolHandler ["http-nio-0.0.0.0-9000"]
2019.06.26 11:38:01 INFO  web[o.s.s.a.TomcatAccessLog] Web server is stopped
2019.06.26 11:38:01 INFO  app[o.s.p.m.Monitor] Process[web] is stopped
2019.06.26 11:38:01 INFO  app[o.s.p.m.Monitor] Process[es] is stopping
2019.06.26 11:38:02 INFO   es[o.s.p.StopWatcher]  Stopping process
2019.06.26 11:38:02 INFO   es[o.elasticsearch.node]  [sonar-1561529196380] stopping ...
2019.06.26 11:38:02 INFO   es[o.elasticsearch.node]  [sonar-1561529196380] stopped
2019.06.26 11:38:02 INFO   es[o.elasticsearch.node]  [sonar-1561529196380] closing ...
2019.06.26 11:38:02 INFO   es[o.elasticsearch.node]  [sonar-1561529196380] closed
2019.06.26 11:38:02 INFO  app[o.s.p.m.Monitor] Process[es] is stopped
<-- Wrapper Stopped**

**Comment by racodond** [comment]
Hi,

Unfortunately, I no longer support my SonarQube plugins.

Regards,

David
